import os
from get_intent_checks_data import *

white = os.getenv("white")
black = os.getenv("black")
BASE_URL = os.getenv("BASE_URL")
TOKEN = os.getenv("TOKEN")

automatic_checks_dict = {
            'Inventory Row': {
                'CATEGORIES': 'Inventory', 'CHECK NAME': white,
                'GREEN': white,
                'BLUE': white,
                'AMBER': white,
                'RED': white,
                'TAB': white,
                'GREEN THRESHOLD': white,
                'BLUE THRESHOLD': white,
                'AMBER THRESHOLD': white,
                'RED THRESHOLD': white,
                  },
            'Software Configuration Register Row': {
                'CATEGORIES': white, 'CHECK NAME': 'Software Configuration Register',
                'GREEN': confreg_green,
                'BLUE': black,
                'AMBER': confreg_amber,
                'RED': black,
                'TAB': 'devices',
                'GREEN THRESHOLD': 'Confreg other than 0x0',
                'BLUE THRESHOLD': black,
                'AMBER THRESHOLD': 'Confreg = 0x0',
                'RED THRESHOLD': black,
                },
			'SFP Modules Row':{
                'CATEGORIES': white, 'CHECK NAME': 'SFP Modules (total)',
                'GREEN': sfp_green,
                'BLUE': black,
				'AMBER': black,
				'RED': black,
				'TAB': 'part-numbers',
				'GREEN THRESHOLD': 'SFP Total Number of Modules.',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'End of Sale Detail':{
                'CATEGORIES': white, 'CHECK NAME': 'End of Sale Detail',
                'GREEN': eos_green,
                'BLUE': eos_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'end-of-life',
				'GREEN THRESHOLD': 'Have not Announced End-of-Sale yet',
				'BLUE THRESHOLD': 'Have Announced End-of-Sale',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'End of Maintenance Detail':{
                'CATEGORIES': white, 'CHECK NAME': 'End of Maintenance Detail',
                'GREEN': eom_green,
                'BLUE': black,
				'AMBER': eom_amber,
				'RED': black,
				'TAB': 'end-of-life',
				'GREEN THRESHOLD': 'Have not Announced End-of-Maintenance',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'Have Announced End-of-Maintenance',
				'RED THRESHOLD': black,
				},
			'End of Support Detail':{
                'CATEGORIES': white, 'CHECK NAME': 'End of Support Detail',
                'GREEN': eosup_green,
                'BLUE': black,
				'AMBER': black,
				'RED': eosup_red,
				'TAB': 'end-of-life',
				'GREEN THRESHOLD': 'Have not Announced End-of-Support',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': 'Have Announced End-of-Support',
				},
			'End of Sale':{
                'CATEGORIES': white, 'CHECK NAME': 'End of Sale',
                'GREEN': sale_green,
                'BLUE': sale_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'end-of-life',
				'GREEN THRESHOLD': 'The date of End-of-Sale has not passed',
				'BLUE THRESHOLD': 'The date of End-of-Sale has passed',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'End of Maintenance':{
                'CATEGORIES': white, 'CHECK NAME': 'End of Maintenance',
                'GREEN': maintenance_green,
                'BLUE': black,
				'AMBER': maintenance_amber,
				'RED': black,
				'TAB': 'end-of-life',
				'GREEN THRESHOLD': 'The date of End-of-Maintenance has not passed',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'The date of End-of-Maintenance has passed',
				'RED THRESHOLD': black,
				},
			'End of Support':{
                'CATEGORIES': white, 'CHECK NAME': 'End of Support',
                'GREEN': support_green,
                'BLUE': black,
				'AMBER': black,
				'RED': support_red,
				'TAB': 'end-of-life',
				'GREEN THRESHOLD': 'The date of End-of-Support has not passed',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': 'The date of End-of-Support has passed',
				},
			'Device Reload Reason':{
                'CATEGORIES': white, 'CHECK NAME': 'Device Reload Reason',
                'GREEN': reload_green,
                'BLUE': reload_blue,
				'AMBER': reload_amber,
				'RED': reload_red,
				'TAB': 'devices',
				'GREEN THRESHOLD': 'Reload Occurred More than 3 months ago',
				'BLUE THRESHOLD': 'Reload Reason Contains Failure and happened in the last 3 months',
				'AMBER THRESHOLD': 'Reload Reason Contains Failure and occurred in the last 1 week; or a failure '
								   'that was not due to power issues in the last 3 months',
				'RED THRESHOLD': 'Reload Reason contains a failure that was not due to a power issue'
								 ' or miscellaneous reason and occurred in the past 24 hours',
				},
			'Device Memory Usage (%)':{
                'CATEGORIES': white, 'CHECK NAME': 'Device Memory Usage (%)',
                'GREEN': memory_green,
                'BLUE': memory_blue,
				'AMBER': memory_amber,
				'RED': memory_red,
				'TAB': 'devices',
				'GREEN THRESHOLD': 'Device Memory Utilization is below 50%',
				'BLUE THRESHOLD': 'Device Memory Utilization is between 50% and 70%',
				'AMBER THRESHOLD': 'Device Memory Utilization is between 70% and 85%',
				'RED THRESHOLD': 'Device Memory Utilization is greater than 85%',
				},
			'Device Uptime':{
                'CATEGORIES': white, 'CHECK NAME': 'Device Uptime',
                'GREEN': uptime_green,
                'BLUE': uptime_blue,
				'AMBER': uptime_amber,
				'RED': uptime_red,
				'TAB': 'devices',
				'GREEN THRESHOLD': 'Longer than 1 week but less than 3 years',
				'BLUE THRESHOLD': 'Longer than 3 years',
				'AMBER THRESHOLD': 'Less than 1 week',
				'RED THRESHOLD': 'Less than 1 day',
				},
			'Interfaces':{
                'CATEGORIES': 'Interfaces', 'CHECK NAME': white,
                'GREEN': white,
                'BLUE': white,
				'AMBER': white,
				'RED': white,
				'TAB': white,
				'GREEN THRESHOLD': white,
				'BLUE THRESHOLD': white,
				'AMBER THRESHOLD': white,
				'RED THRESHOLD': white,
				},
			'Interface Operational State':{
                'CATEGORIES': white, 'CHECK NAME': 'Interface Operational State',
                'GREEN': operate_green,
                'BLUE': operate_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'interfaces',
				'GREEN THRESHOLD': 'Admin down OR operationally up',
				'BLUE THRESHOLD': 'Admin up AND operationally down',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'Interface Duplex':{
                'CATEGORIES': white, 'CHECK NAME': 'Interface Duplex',
                'GREEN': black,
                'BLUE': duplex_blue,
				'AMBER': duplex_amber,
				'RED': black ,
				'TAB': 'interfaces',
				'GREEN THRESHOLD': black,
				'BLUE THRESHOLD': 'Missing duplex information.',
				'AMBER THRESHOLD': 'Duplex mismatched information.',
				'RED THRESHOLD': black,
				},
			'Maximum Transmission Unit (MTU)':{
                'CATEGORIES': white, 'CHECK NAME': 'Maximum Transmission Unit (MTU)',
                'GREEN': mtu_green,
                'BLUE': mtu_blue,
				'AMBER': mtu_amber,
				'RED': black,
				'TAB': 'mtu',
				'GREEN THRESHOLD': 'MTU Detected',
				'BLUE THRESHOLD': 'Transit Links missing MTU on either side.',
				'AMBER THRESHOLD': 'Transit Links with inconsistent MTUs on either side',
				'RED THRESHOLD': black,
				},
			'Error-Disabled Interfaces (total)':{
                'CATEGORIES': white, 'CHECK NAME': 'Error-Disabled Interfaces (total)',
                'GREEN': black,
                'BLUE': black,
				'AMBER': err_amber,
				'RED': black,
				'TAB': 'errdisabled',
				'GREEN THRESHOLD': black,
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'Number of err-disabled interfaces',
				'RED THRESHOLD': black,
				},
			'Switched Port Analyzer (SPAN) ports (total)':{
                'CATEGORIES': white, 'CHECK NAME': 'Switched Port Analyzer (SPAN) ports (total)',
                'GREEN': span_green,
                'BLUE': black,
				'AMBER': black,
				'RED': black,
				'TAB': 'interfaces',
				'GREEN THRESHOLD': 'Interfaces with SPAN configured',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'Edge-Ports with Multiple Neighbors':{
                'CATEGORIES': white, 'CHECK NAME': 'Edge-Ports with Multiple Neighbors',
                'GREEN': edge_green,
                'BLUE': edge_blue,
				'AMBER': edge_amber,
				'RED': edge_red,
				'TAB': 'switchports',
				'GREEN THRESHOLD': 'Non-trunk edge-ports with two or less mac-addresses detected.',
				'BLUE THRESHOLD': 'Non-trunk edge-ports with 3-20 mac-addresses detected.',
				'AMBER THRESHOLD': 'Non-trunk edge-ports with 20-100 mac-addresses detected.',
				'RED THRESHOLD': 'Non-trunk edge-ports with mroe than 100 mac-addresses detected.',
				},
			'Juniper Cluster Link Status':{
                'CATEGORIES': white, 'CHECK NAME': 'Juniper Cluster Link Status',
                'GREEN': juniper_green,
                'BLUE': black,
				'AMBER': juniper_amber,
				'RED': black,
				'TAB': 'juniper-cluster-srx',
				'GREEN THRESHOLD': 'Control or Fabric links that are UP',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'Control or Fabric links that are not UP',
				'RED THRESHOLD': black,
				},
			'Edge Port Security':{
                'CATEGORIES': white, 'CHECK NAME': 'Edge Port Security',
                'GREEN': portsec_green,
                'BLUE': portsec_blue,
				'AMBER': portsec_amber,
				'RED': black,
				'TAB': 'secure-ports-interfaces',
				'GREEN THRESHOLD': 'Edge switching interfaces with security method 802.1X applied.',
				'BLUE THRESHOLD': 'Edge switching interfaces with unknown security method.',
				'AMBER THRESHOLD': 'Edge switching interfaces with security method other than 802.1X applied.',
				'RED THRESHOLD': black,
				},
			'Paired Devices With Different Configs':{
                'CATEGORIES': white, 'CHECK NAME': 'Paired Devices With Different Configs',
                'GREEN': pcdiff_green,
                'BLUE': black,
				'AMBER': black,
				'RED': pcdiff_red,
				'TAB': 'mlag-vpc',
				'GREEN THRESHOLD': 'Paired devices have consistent configs',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': 'Paired devices have inconsistent configs',
				},
			'MLAG Pairs Status':{
                'CATEGORIES': white, 'CHECK NAME': 'MLAG Pairs Status',
                'GREEN': mlag_green,
                'BLUE': black,
				'AMBER': mlag_amber,
				'RED': mlag_red,
				'TAB': 'mlag-pairs',
				'GREEN THRESHOLD': 'Primary and Secondary are UP',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'Either primary or backup is not UP',
				'RED THRESHOLD': 'Both Pairs are not up',
				},
			'Peer Link':{
                'CATEGORIES': white, 'CHECK NAME': 'Peer Link',
                'GREEN': vpcpl_green,
                'BLUE': black,
				'AMBER': black,
				'RED': vpcpl_red,
				'TAB': 'mlag-peer-links',
				'GREEN THRESHOLD': 'Peer Link configured',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': 'Peer Link is not cofigured',
				},
			'Cisco VPC Status':{
                'CATEGORIES': white, 'CHECK NAME': 'Cisco VPC Status',
                'GREEN': vpcst_green,
                'BLUE': vpcst_blue,
				'AMBER': black,
				'RED': vpcst_red,
				'TAB': 'mlag-vpc',
				'GREEN THRESHOLD': 'VPC Status is UP',
				'BLUE THRESHOLD': 'Role is not primary or secondary',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': 'VPC Status is not UP',
				},
			'Endpoints':{
                'CATEGORIES': 'Endpoints', 'CHECK NAME': white,
                'GREEN': white,
                'BLUE': white,
				'AMBER': white,
				'RED': white,
				'TAB': white,
				'GREEN THRESHOLD': white,
				'BLUE THRESHOLD': white,
				'AMBER THRESHOLD': white,
				'RED THRESHOLD': white,
				},
			'Endpoints Resolution':{
                'CATEGORIES': white, 'CHECK NAME': 'Endpoints Resolution',
                'GREEN': endpres_green,
                'BLUE': endpres_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'hosts',
				'GREEN THRESHOLD': 'The total number of MAC addresses that have assigned IP Address information',
				'BLUE THRESHOLD': 'The total number of MAC addresses that have not assigned any IP Address information.',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'IP Phone - Connected MACs':{
                'CATEGORIES': white, 'CHECK NAME': 'IP Phone - Connected MACs',
                'GREEN': phonemacs_green,
                'BLUE': black,
				'AMBER': phonemacs_amber,
				'RED': black,
				'TAB': 'phones',
				'GREEN THRESHOLD': 'IP phones with a single MAC address connected behind the phone.',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'IP phones with multiple MAC addresses connected behind the phone',
				'RED THRESHOLD': black,
				},
			'Performance':{
                'CATEGORIES': 'Performance', 'CHECK NAME': white,
                'GREEN': white,
                'BLUE': white,
				'AMBER': white,
				'RED': white,
				'TAB': white,
				'GREEN THRESHOLD': white,
				'BLUE THRESHOLD': white,
				'AMBER THRESHOLD': white,
				'RED THRESHOLD': white,
				},
			'Transfer Rates (inbound)':{
                'CATEGORIES': white, 'CHECK NAME': 'Transfer Rates (inbound)',
                'GREEN': transfer_rates_in_green,
                'BLUE': transfer_rates_in_blue,
				'AMBER': transfer_rates_in_amber,
				'RED': transfer_rates_in_red,
				'TAB': 'transfer-rates-inbound',
				'GREEN THRESHOLD': 'Interfaces with Inbound Value Impact value equal to zero',
				'BLUE THRESHOLD': 'Interfaces with Inbound Loss Impact value between 1 and 5.',
				'AMBER THRESHOLD': 'Interfaces with Inbound Loss Impact value between 5 and 10.',
				'RED THRESHOLD': 'Interfaces with Inbound Loss Impact value greater than 10.',
				},
			'Transfer Rates (outbound)':{
                'CATEGORIES': white, 'CHECK NAME': 'Transfer Rates (outbound)',
                'GREEN': transfer_rates_out_green,
                'BLUE': transfer_rates_out_blue,
				'AMBER': transfer_rates_out_amber,
				'RED': transfer_rates_out_red,
				'TAB': 'transfer-rates-outbound',
				'GREEN THRESHOLD': 'Interfaces with Outbound Loss Impact value equal to zero.',
				'BLUE THRESHOLD': 'Interfaces with Outbound Loss Impact value between 1 and 5.',
				'AMBER THRESHOLD': 'Interfaces with Outbound Loss Impact value between 5 and 10.',
				'RED THRESHOLD': 'Interfaces with Outbound Loss Impact value greater than 10.',
				},
			'Transfer Rates (bidirectional)':{
                'CATEGORIES': white, 'CHECK NAME': 'Transfer Rates (bidirectional)',
                'GREEN': transfer_rates_bi_green,
                'BLUE': transfer_rates_bi_blue,
				'AMBER': transfer_rates_bi_amber,
				'RED': transfer_rates_bi_red,
				'TAB': 'transfer-rates-bidirectional',
				'GREEN THRESHOLD': 'Interfaces with Bidirectional Loss Impact value equal to zero.',
				'BLUE THRESHOLD': 'Interfaces with Bidirectional Loss Impact value between 1 and 5.',
				'AMBER THRESHOLD': 'Interfaces with Bidirectional Loss Impact value between 5 and 10.',
				'RED THRESHOLD': 'Interfaces with Bidirectional Loss Impact value greater than 10.',
				},
			'Transfer Rates (device-inbound)':{
                'CATEGORIES': white, 'CHECK NAME': 'Transfer Rates (device-inbound)',
                'GREEN': transfer_rates_dev_in_green,
                'BLUE': transfer_rates_dev_in_blue,
				'AMBER': transfer_rates_dev_in_amber,
				'RED': transfer_rates_dev_in_red,
				'TAB': 'transfer-rates-inbound-device',
				'GREEN THRESHOLD': 'Devices with Inbound Value Impact value equal to zero',
				'BLUE THRESHOLD': 'Devices with Inbound Loss Impact value between 1 and 5.',
				'AMBER THRESHOLD': 'Devices with Inbound Loss Impact value between 5 and 10.',
				'RED THRESHOLD': 'Devices with Inbound Loss Impact value greater than 10.',
				},
			'Transfer Rates (device-outbound)':{
                'CATEGORIES': white, 'CHECK NAME': 'Transfer Rates (device-outbound)',
                'GREEN': transfer_rates_dev_out_green,
                'BLUE': transfer_rates_dev_out_blue,
				'AMBER': transfer_rates_dev_out_amber,
				'RED': transfer_rates_dev_out_red,
				'TAB': 'transfer-rates-outbound-device',
				'GREEN THRESHOLD': 'Devices with Outbound Loss Impact value equal to zero.',
				'BLUE THRESHOLD': 'Devices with Outbound Loss Impact value between 1 and 5.',
				'AMBER THRESHOLD': 'Devices with Outbound Loss Impact value between 5 and 10.',
				'RED THRESHOLD': 'Devices with Outbound Loss Impact value greater than 10.',
				},
			'Transfer Rates (device-bidirectional)':{
                'CATEGORIES': white, 'CHECK NAME': 'Transfer Rates (device-bidirectional)',
                'GREEN': transfer_rates_dev_bi_green,
                'BLUE': transfer_rates_dev_bi_blue,
				'AMBER': transfer_rates_dev_bi_amber,
				'RED': transfer_rates_dev_bi_red,
				'TAB': 'transfer-rates-bidirectional-device',
				'GREEN THRESHOLD': 'Devices with Bidirectional Loss Impact value equal to zero.',
				'BLUE THRESHOLD': 'Devices with Bidirectional Loss Impact value between 1 and 5.',
				'AMBER THRESHOLD': 'Devices with Bidirectional Loss Impact value between 5 and 10.',
				'RED THRESHOLD': 'Devices with Bidirectional Loss Impact value greater than 10.',
				},
			'Input errors impact':{
                'CATEGORIES': white, 'CHECK NAME': 'Input errors impact',
                'GREEN': input_errors_green,
                'BLUE': input_errors_blue,
				'AMBER': input_errors_amber,
				'RED': input_errors_red,
				'TAB': 'errors-inbound',
				'GREEN THRESHOLD': 'Interfaces with Input Errors Impact value equal to zero.',
				'BLUE THRESHOLD': 'Interfaces with Input Errors Impact value between 1 and 5.',
				'AMBER THRESHOLD': 'Interfaces with Input Errors Impact value between 5 and 10.',
				'RED THRESHOLD': 'Interfaces with Input Errors Impact value greater than 10.',
				},
			'Output errors impact':{
                'CATEGORIES': white, 'CHECK NAME': 'Output errors impact',
                'GREEN': output_errors_green,
                'BLUE': output_errors_blue,
				'AMBER': output_errors_amber,
				'RED': output_errors_red,
				'TAB': 'errors-outbound',
				'GREEN THRESHOLD': 'Interfaces with Output Errors Impact value equal to zero.',
				'BLUE THRESHOLD': 'Interfaces with Output Errors Impact value between 1 and 5.',
				'AMBER THRESHOLD': 'Interfaces with Output Errors Impact value between 5 and 10.',
				'RED THRESHOLD': 'Interfaces with Output Errors Impact value greater than 10.',
				},
			'Error Rates (bidirectional)':{
                'CATEGORIES': white, 'CHECK NAME': 'Error Rates (bidirectional)',
                'GREEN': error_rates_bi_green,
                'BLUE': error_rates_bi_blue,
				'AMBER': error_rates_bi_amber,
				'RED': error_rates_bi_red,
				'TAB': 'errors-bidirectional',
				'GREEN THRESHOLD': 'Interfaces with Bidirectional Errors Impact value equal to zero.',
				'BLUE THRESHOLD': 'Interfaces with Bidirectional Errors Impact value between 1 and 5.',
				'AMBER THRESHOLD': 'Interfaces with Bidirectional Errors Impact value between 5 and 10.',
				'RED THRESHOLD': 'Interfaces with Bidirectional Errors Impact value greater than 10.',
				},
			'Device input errors impact':{
                'CATEGORIES': white, 'CHECK NAME': 'Device input errors impact',
                'GREEN': dev_in_errors_green,
                'BLUE': dev_in_errors_blue,
				'AMBER': dev_in_errors_amber,
				'RED': dev_in_errors_red,
				'TAB': 'errors-inbound-device',
				'GREEN THRESHOLD': 'Devices with Input Errors Impact value equal to zero.',
				'BLUE THRESHOLD': 'Devices with Input Errors Impact value between 1 and 5.',
				'AMBER THRESHOLD': 'Devices with Input Errors Impact value between 5 and 10.',
				'RED THRESHOLD': 'Devices with Input Errors Impact value greater than 10.',
				},
			'Device output errors impact':{
                'CATEGORIES': white, 'CHECK NAME': 'Device output errors impact',
                'GREEN': dev_out_errors_green,
                'BLUE': dev_out_errors_blue,
				'AMBER': dev_out_errors_amber,
				'RED': dev_out_errors_red,
				'TAB': 'errors-outbound-device',
				'GREEN THRESHOLD': 'Devices with Output Errors Impact value equal to zero.',
				'BLUE THRESHOLD': 'Devices with Output Errors Impact value between 1 and 5.',
				'AMBER THRESHOLD': 'Devices with Output Errors Impact value between 5 and 10.',
				'RED THRESHOLD': 'Devices with Output Errors Impact value greater than 10.',
				},
			'Error Rates (device-bidirectional)':{
                'CATEGORIES': white, 'CHECK NAME': 'Error Rates (device-bidirectional)',
                'GREEN': dev_bi_errors_green,
                'BLUE': dev_bi_errors_blue,
				'AMBER': dev_bi_errors_amber,
				'RED': dev_bi_errors_red,
				'TAB': 'errors-bidirectional-device',
				'GREEN THRESHOLD': 'Devices with Bidirectional Errors Impact value equal to zero.',
				'BLUE THRESHOLD': 'Devices with Bidirectional Errors Impact value between 1 and 5.',
				'AMBER THRESHOLD': 'Devices with Bidirectional Errors Impact value between 5 and 10.',
				'RED THRESHOLD': 'Devices with Bidirectional Errors Impact value greater than 10.',
				},
			'Input drops impact':{
                'CATEGORIES': white, 'CHECK NAME': 'Input drops impact',
                'GREEN': input_drops_green,
                'BLUE': input_drops_blue,
				'AMBER': input_drops_amber,
				'RED': input_drops_red,
				'TAB': 'drops-inbound',
				'GREEN THRESHOLD': 'Interfaces with Input Drops Impact value equal to zero.',
				'BLUE THRESHOLD': 'Interfaces with Input Drops Impact value between 1 and 5.',
				'AMBER THRESHOLD': 'Interfaces with Input Drops Impact value between 5 and 10.',
				'RED THRESHOLD': 'Interfaces with Input Drops Impact value greater than 10.',
				},
			'Output drops impact':{
                'CATEGORIES': white, 'CHECK NAME': 'Output drops impact',
                'GREEN': output_drops_green,
                'BLUE': output_drops_blue,
				'AMBER': output_drops_amber,
				'RED': output_drops_red,
				'TAB': 'drops-outbound',
				'GREEN THRESHOLD': 'Interfaces with Output Drops Impact value equal to zero.',
				'BLUE THRESHOLD': 'Interfaces with Output Drops Impact value between 1 and 5.',
				'AMBER THRESHOLD': 'Interfaces with Output Drops Impact value between 5 and 10.',
				'RED THRESHOLD': 'Interfaces with Output Drops Impact value greater than 10.',
				},
			'Drop Rates (bidirectional)':{
                'CATEGORIES': white, 'CHECK NAME': 'Drop Rates (bidirectional)',
                'GREEN': drop_rates_bi_green,
                'BLUE': drop_rates_bi_blue,
				'AMBER': drop_rates_bi_amber,
				'RED': drop_rates_bi_red,
				'TAB': 'drops-bidirectional',
				'GREEN THRESHOLD': 'Interfaces with Bidirectional Drops Impact value equal to zero.',
				'BLUE THRESHOLD': 'Interfaces with Bidirectional Drops Impact value between 1 and 5.',
				'AMBER THRESHOLD': 'Interfaces with Bidirectional Drops Impact value between 5 and 10.',
				'RED THRESHOLD': 'Interfaces with Bidirectional Drops Impact value greater than 10.',
				},
			'Device input drops impact':{
                'CATEGORIES': white, 'CHECK NAME': 'Device input drops impact',
                'GREEN': dev_in_drops_green,
                'BLUE': dev_in_drops_blue,
				'AMBER': dev_in_drops_amber,
				'RED': dev_in_drops_red,
				'TAB': 'drops-inbound-device',
				'GREEN THRESHOLD': 'Devices with Input Drops Impact value equal to zero.',
				'BLUE THRESHOLD': 'Devices with Input Drops Impact value between 1 and 5.',
				'AMBER THRESHOLD': 'Devices with Input Drops Impact value between 5 and 10.',
				'RED THRESHOLD': 'Devices with Input Drops Impact value greater than 10.',
				},
			'Device output drops impact':{
                'CATEGORIES': white, 'CHECK NAME': 'Device output drops impact',
                'GREEN': dev_out_drops_green,
                'BLUE': dev_out_drops_blue,
				'AMBER': dev_out_drops_amber,
				'RED': dev_out_drops_red,
				'TAB': 'drops-outbound-device',
				'GREEN THRESHOLD': 'Devices with Output Drops Impact value equal to zero.',
				'BLUE THRESHOLD': 'Devices with Output Drops Impact value between 1 and 5.',
				'AMBER THRESHOLD': 'Devices with Output Drops Impact value between 5 and 10.',
				'RED THRESHOLD': 'Devices with Output Drops Impact value greater than 10.',
				},
			'Drop Rates (device-bidirectional)':{
                'CATEGORIES': white, 'CHECK NAME': 'Drop Rates (device-bidirectional)',
                'GREEN': drop_rates_dev_bi_green,
                'BLUE': drop_rates_dev_bi_blue,
				'AMBER': drop_rates_dev_bi_amber,
				'RED': drop_rates_dev_bi_red,
				'TAB': 'drops-bidirectional-device',
				'GREEN THRESHOLD': 'Devices with Bidirectional Drops Impact value equal to zero.',
				'BLUE THRESHOLD': 'Devices with Bidirectional Drops Impact value between 1 and 5.',
				'AMBER THRESHOLD': 'Devices with Bidirectional Drops Impact value between 5 and 10.',
				'RED THRESHOLD': 'Devices with Bidirectional Drops Impact value greater than 10.',
				},
			'Access Point - Radio Signal Impact':{
                'CATEGORIES': white, 'CHECK NAME': 'Access Point - Radio Signal Impact',
                'GREEN': acc_pt_radio_signal_green,
                'BLUE': acc_pt_radio_signal_blue,
				'AMBER': acc_pt_radio_signal_amber,
				'RED': acc_pt_radio_signal_red,
				'TAB': 'access-points',
				'GREEN THRESHOLD': 'Access points zero impact value',
				'BLUE THRESHOLD': 'Access points with the impact value within 1 and 6.',
				'AMBER THRESHOLD': 'Access points with the impact value within 6 and 10',
				'RED THRESHOLD': 'Access points with the impact value greater than 10.',
				},
			'Access Point - Connected Clients':{
                'CATEGORIES': white, 'CHECK NAME': 'Access Point - Connected Clients',
                'GREEN': acc_pt_con_green,
                'BLUE': acc_pt_con_blue,
				'AMBER': acc_pt_con_amber,
				'RED': acc_pt_con_red,
				'TAB': 'access-points',
				'GREEN THRESHOLD': 'Access points with less than 50 clients connected.',
				'BLUE THRESHOLD': 'Access points within 50 and 80 clients connected',
				'AMBER THRESHOLD': 'Access points within 80 and 100 clients connected.',
				'RED THRESHOLD': 'Access points with more than 100 clients connected.',
				},
			'Wireless Client - RSSI':{
                'CATEGORIES': white, 'CHECK NAME': 'Wireless Client - RSSI',
                'GREEN': rssi_green,
                'BLUE': rssi_blue,
				'AMBER': rssi_amber,
				'RED': rssi_red,
				'TAB': 'wireless-clients',
				'GREEN THRESHOLD': 'Connected clients with Signal Strength (dBm) greater than -60',
				'BLUE THRESHOLD': 'Connected clients with Signal Strength (dBm) within -60 and -67',
				'AMBER THRESHOLD': 'Connected clients with Signal Strength (dBm) within -67 and -80',
				'RED THRESHOLD': 'Connected clients with Signal Strength (dBm) lower than -80.',
				},
			'QoS EF Class Drops':{
                'CATEGORIES': white, 'CHECK NAME': 'QoS EF Class Drops',
                'GREEN': qos_ef_green,
                'BLUE': black,
				'AMBER': qos_ef_amber,
				'RED': black,
				'TAB': 'policy-map',
				'GREEN THRESHOLD': 'Classes carrying Expedited Forwarding traffic with drop rate equal to 0',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'Classes carrying Expedited Forwarding traffic with drop rate greater than 0',
				'RED THRESHOLD': black,
				},
			'Wireless Client - SNR':{
                'CATEGORIES': white, 'CHECK NAME': 'Wireless Client - SNR',
                'GREEN': snr_green,
                'BLUE': snr_blue,
				'AMBER': snr_amber,
				'RED': snr_red,
				'TAB': 'wireless-clients',
				'GREEN THRESHOLD': 'Connected clients with SNR greater than 25.',
				'BLUE THRESHOLD': 'Connected clients with SNR within 25 and 15.',
				'AMBER THRESHOLD': 'Connected clients with SNR within 15 and 10.',
				'RED THRESHOLD': 'Connected clients with SNR lower than 10.',
				},
			'End-to-End Path Flooding':{
                'CATEGORIES': white, 'CHECK NAME': 'End-to-End Path Flooding',
                'GREEN': path_flooding_green,
                'BLUE': black,
				'AMBER': path_flooding_amber,
				'RED': black,
				'TAB': 'path-verifications',
				'GREEN THRESHOLD': 'End-to-End paths without any MAC flooding detected.',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'End-to-End paths with MAC flooding detected.',
				'RED THRESHOLD': black,
				},
			'End-to-End Path Verification':{
                'CATEGORIES': white, 'CHECK NAME': 'End-to-End Path Verification',
                'GREEN': path_verify_green,
                'BLUE': black,
				'AMBER': path_verify_amber,
				'RED': path_verify_red,
				'TAB': 'path-verifications',
				'GREEN THRESHOLD': 'End-to-End path verification that are in an expected state (OK or FAIL)',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'End-to-End path verifcations that are in an ERROR state',
				'RED THRESHOLD': 'End-to-End path verifications that are not in an expected state (OK or FAIL)',
				},
			'Port-Channel Output Balancing Variance':{
                'CATEGORIES': white, 'CHECK NAME': 'Port-Channel Output Balancing Variance',
                'GREEN': pc_out_var_green,
                'BLUE': pc_out_var_blue,
				'AMBER': pc_out_var_amber,
				'RED': pc_out_var_red,
				'TAB': 'outbound-balancing-table',
				'GREEN THRESHOLD': 'Aggregated interfaces with output balancing variance lower than 500.',
				'BLUE THRESHOLD': 'Aggregated interfaces with output blancing variance higher than 500 and'
								  ' Rage below 30Mbps.',
				'AMBER THRESHOLD': 'Aggregated interfaces with output balancing variance higher than 500 '
								   'and Rate above 30Mbps',
				'RED THRESHOLD': 'Aggregated interfaces with output balancing variance greater than 500 '
								 'and Rate above 1000Mbps',
				},
			'Port-Channel Input Balancing Variance':{
                'CATEGORIES': white, 'CHECK NAME': 'Port-Channel Input Balancing Variance',
                'GREEN': pc_in_var_green,
                'BLUE': pc_in_var_blue,
				'AMBER': pc_in_var_amber ,
				'RED': pc_in_var_red,
				'TAB': 'inbound-balancing-table',
				'GREEN THRESHOLD': 'Aggregated interfaces with input balancing variance lower than 500.',
				'BLUE THRESHOLD': 'Aggregated interfaces with input blancing variance higher than 500 and'
								  ' Rage below 30Mbps.',
				'AMBER THRESHOLD': 'Aggregated interfaces with input balancing variance higher than 500 '
								   'and Rate above 30Mbps',
				'RED THRESHOLD': 'Aggregated interfaces with input balancing variance greater than 500 '
								 'and Rate above 1000Mbps',
				},
			'MRoute RPF Errors':{
                'CATEGORIES': white, 'CHECK NAME': 'MRoute RPF Errors',
                'GREEN': mroute_rpf_green,
                'BLUE': black,
				'AMBER': mroute_rpf_amber,
				'RED': black,
				'TAB': 'mroute-counters',
				'GREEN THRESHOLD': 'MRoutes without any detected errors per second compared to previous'
								   ' discovery records.',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'MRoutes with detected errors per seconds compared to previous discovery records.',
				'RED THRESHOLD': black,
				},
			'Access Point - Signal-to-Noise Ratio (SNR)':{
                'CATEGORIES': white, 'CHECK NAME': 'Access Point - Signal-to-Noise Ratio (SNR)',
                'GREEN': ap_snr_green ,
                'BLUE': ap_snr_blue,
				'AMBER': ap_snr_amber,
				'RED': ap_snr_red,
				'TAB': 'access-points',
				'GREEN THRESHOLD': 'Access points with average SNR greater than 25 for APs with at least one client',
				'BLUE THRESHOLD': 'Access points with average SNR within 25 and 15 for APs with at least one client.',
				'AMBER THRESHOLD': 'Access points with average SNR within 15 and 10 for APs with at least one client.',
				'RED THRESHOLD': 'Access points with average SNR lower than 10 for APs with at least one client.',
				},
			'MRoute Other Errors':{
                'CATEGORIES': white, 'CHECK NAME': 'MRoute Other Errors',
                'GREEN': mroute_other_green,
                'BLUE': black,
				'AMBER': mroute_other_amber,
				'RED': black,
				'TAB': 'mroute-counters',
				'GREEN THRESHOLD': 'MRoutes without any detected errors per seconds compared to previous '
								   'discovery records.  (TTL, Empty OIL, Encap, Other)',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'MRoutes with detected errors per seconds compared to previous discovery records.'
								   '  (TTL, Empty OIL, Encap, Other)',
				'RED THRESHOLD': black,
				},
			'Environment':{
                'CATEGORIES': 'Environment', 'CHECK NAME': white,
                'GREEN': white,
                'BLUE': white,
				'AMBER': white,
				'RED': white,
				'TAB': white,
				'GREEN THRESHOLD': white,
				'BLUE THRESHOLD': white,
				'AMBER THRESHOLD': white,
				'RED THRESHOLD': white,
				},
			'Power-Supply State':{
                'CATEGORIES': white, 'CHECK NAME': 'Power-Supply State',
                'GREEN': pwr_state_green,
                'BLUE': pwr_state_blue,
				'AMBER': black,
				'RED': pwr_state_red,
				'TAB': 'power-supplies',
				'GREEN THRESHOLD': 'Power-supplies that are in healthy state (ok, good, normal, online)',
				'BLUE THRESHOLD': 'Power-supplies that are neither in expected healthy state nor in the fail state',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': 'Power-supplies that are not in healthy state (fail, fault, present).',
				},
			'Power-Supply Fan State':{
                'CATEGORIES': white, 'CHECK NAME': 'Power-Supply Fan State',
                'GREEN': pwr_fan_green,
                'BLUE': pwr_fan_blue,
				'AMBER': black,
				'RED': pwr_fan_red,
				'TAB': 'power-supplies-fans',
				'GREEN THRESHOLD': 'Power-supply fans that are in healthy state (ok, good, normal,'
								   ' running successfully).',
				'BLUE THRESHOLD': 'Power-supply fans that are neither in expected healthy state nor '
								  'in the fail state.',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': 'Power-supply fans that are not in healthy state (fail, fault).',
				},
			'Module State':{
                'CATEGORIES': white, 'CHECK NAME': 'Module State',
                'GREEN': mod_state_green,
                'BLUE': mod_state_blue,
				'AMBER': black,
				'RED': mod_state_red,
				'TAB': 'poe-modules',
				'GREEN THRESHOLD': 'Modules that are in healthy state (powered-up).',
				'BLUE THRESHOLD': 'Modules that are neither in expected healthy state nor in the fail state.',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': 'Modules that are in faulty state (err).',
				},
			'PoE Interface State':{
                'CATEGORIES': white, 'CHECK NAME': 'PoE Interface State',
                'GREEN': poe_state_green,
                'BLUE': poe_state_blue,
				'AMBER': poe_state_amber,
				'RED': black,
				'TAB': 'poe-interfaces',
				'GREEN THRESHOLD': 'Interfaces that are distributing power over ethernet and are operational (ON).',
				'BLUE THRESHOLD': 'Interfaces that are capable of distributing power over ethernet and are '
								  'not operational (OFF).',
				'AMBER THRESHOLD': 'Interfaces that are capable of distributing power over ethernet and have '
								   'faulty operational status (FAULT, ERROR).',
				'RED THRESHOLD': black,
				},
			'Stack Port State':{
                'CATEGORIES': white, 'CHECK NAME': 'Stack Port State',
                'GREEN': stack_green,
                'BLUE': stack_blue,
				'AMBER': stack_amber,
				'RED': black,
				'TAB': 'stacks-connections',
				'GREEN THRESHOLD': 'Stack interfaces that are operational, OK detected status.',
				'BLUE THRESHOLD': 'Represents stack interfaces with other than OK or DOWN '
								  'detected operational status.',
				'AMBER THRESHOLD': 'Stack interfaces that are not operational, DOWN detected status.',
				'RED THRESHOLD': black,
				},
			'PoE Module Watts Used (%)':{
                'CATEGORIES': white, 'CHECK NAME': 'PoE Module Watts Used (%)',
                'GREEN': poe_watts_green,
                'BLUE': poe_watts_blue,
				'AMBER': poe_watts_amber,
				'RED': poe_watts_red,
				'TAB': 'poe-modules',
				'GREEN THRESHOLD': 'Watts used per hardware module is below 60% of its capacity.',
				'BLUE THRESHOLD': 'Watts used per hardware module is above 60% of its capacity.',
				'AMBER THRESHOLD': 'Watts used per module is above 80% of its capacity.',
				'RED THRESHOLD': "Watts used per hardware module is above 95% of it's capacity",
				},
			'Fan Module State':{
                'CATEGORIES': white, 'CHECK NAME': 'Fan Module State',
                'GREEN': fan_green,
                'BLUE': fan_blue,
				'AMBER': black,
				'RED': fan_red,
				'TAB': 'fans',
				'GREEN THRESHOLD': 'Fan modules that are in healthy state (ok, good, normal, running successfully).',
				'BLUE THRESHOLD': 'Fan modules that are neither in expected healthy state nor in the fail state',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': 'Fan modules that are in faulty state (fail, fault).',
				},
			'Stability':{
                'CATEGORIES': 'Stability', 'CHECK NAME': white,
                'GREEN': white,
                'BLUE': white,
				'AMBER': white,
				'RED': white,
				'TAB': white,
				'GREEN THRESHOLD': white,
				'BLUE THRESHOLD': white,
				'AMBER THRESHOLD': white,
				'RED THRESHOLD': white,
				},
			'OSPF Session Age':{
                'CATEGORIES': white, 'CHECK NAME': 'OSPF Session Age',
                'GREEN': ospf_age_green,
                'BLUE': ospf_age_blue,
				'AMBER': ospf_age_amber,
				'RED': ospf_age_red,
				'TAB': 'ospf-neighbors',
				'GREEN THRESHOLD': 'OSPF sessions with uptime greater than one month',
				'BLUE THRESHOLD': 'OSPF sessions with uptime between one month and one week',
				'AMBER THRESHOLD': 'OSPF sessions with uptime between one week and one day.',
				'RED THRESHOLD': 'OSPF sessions with uptime less than 24 hours.',
				},
			'OSPFv3 Session Age':{
                'CATEGORIES': white, 'CHECK NAME': 'OSPFv3 Session Age',
                'GREEN': ospfv3_age_green,
                'BLUE': ospfv3_age_blue,
				'AMBER': ospfv3_age_amber,
				'RED': ospfv3_age_red,
				'TAB': 'ospf-v3-neighbors',
				'GREEN THRESHOLD': 'OSPFv3 sessions with uptime greater than one month.',
				'BLUE THRESHOLD': 'OSPFv3 sessions with uptime between one month and one week.',
				'AMBER THRESHOLD': 'OSPFv3 sessions with uptime between one week and one day.',
				'RED THRESHOLD': 'OSPFv3 sessions with uptime less than 24 hours.',
				},
			'EIGRP Session Age':{
                'CATEGORIES': white, 'CHECK NAME': 'EIGRP Session Age',
                'GREEN': eigrp_age_green,
                'BLUE': eigrp_age_blue,
				'AMBER': eigrp_age_amber,
				'RED': eigrp_age_red,
				'TAB': 'eigrp-neighbors',
				'GREEN THRESHOLD': 'EIGRP sessions with uptime greater than one month.',
				'BLUE THRESHOLD': 'EIGRP sessions with uptime between one month and one week.',
				'AMBER THRESHOLD': 'EIGRP sessions with uptime between one week and one day.',
				'RED THRESHOLD': 'EIGRP with uptime less than 24 hours.',
				},
			'IS-IS Session Age':{
                'CATEGORIES': white, 'CHECK NAME': 'IS-IS Session Age',
                'GREEN': isis_age_green,
                'BLUE': isis_age_blue,
				'AMBER': isis_age_amber,
				'RED': isis_age_red,
				'TAB': 'is-is-neighbors',
				'GREEN THRESHOLD': 'IS-IS sessions with uptime greater than one month.',
				'BLUE THRESHOLD': 'IS-IS sessions with uptime between one month and one week.',
				'AMBER THRESHOLD': 'IS-IS sessions with uptime between one week and one day.',
				'RED THRESHOLD': 'IS-IS sessions with uptime less than 24 hours.',
				},
			'BGP Session Age':{
                'CATEGORIES': white, 'CHECK NAME': 'BGP Session Age',
                'GREEN': bgp_age_green,
                'BLUE': bgp_age_blue,
				'AMBER': bgp_age_amber,
				'RED': bgp_age_red,
				'TAB': 'bgp-neighbors',
				'GREEN THRESHOLD': 'BGP sessions with uptime greater than one month.',
				'BLUE THRESHOLD': 'BGP sessions with uptime between one month and one week.',
				'AMBER THRESHOLD': 'BGP sessions with uptime between one week and one day.',
				'RED THRESHOLD': 'BGP sessions with uptime less than 24 hours.',
				},
			'LDP Session Age':{
                'CATEGORIES': white, 'CHECK NAME': 'LDP Session Age',
                'GREEN': ldp_age_green,
                'BLUE': ldp_age_blue,
				'AMBER': ldp_age_amber,
				'RED': ldp_age_red,
				'TAB': 'ldp-neighbors',
				'GREEN THRESHOLD': 'LDP sessions with uptime greater than one month.',
				'BLUE THRESHOLD': 'LDP sessions with uptime between one month and one week.',
				'AMBER THRESHOLD': 'LDP sessions with uptime between one week and one day.',
				'RED THRESHOLD': 'LDP sessions with uptime less than 24 hours.',
				},
			'PIM Session Age':{
                'CATEGORIES': white, 'CHECK NAME': 'PIM Session Age',
                'GREEN': pim_age_green,
                'BLUE': pim_age_blue,
				'AMBER': pim_age_amber,
				'RED': pim_age_red,
				'TAB': 'pim-neighbors',
				'GREEN THRESHOLD': 'PIM sessions with uptime greater than one month.',
				'BLUE THRESHOLD': 'PIM sessions with uptime between one month and one week.',
				'AMBER THRESHOLD': 'PIM sessions with uptime between one week and one day.',
				'RED THRESHOLD': 'PIM sessions with uptime less than 24 hours.',
				},
			'DMVPN Tunnel State':{
                'CATEGORIES': white, 'CHECK NAME': 'DMVPN Tunnel State',
                'GREEN': dmvpn_green,
                'BLUE': black,
				'AMBER': dmvpn_amber,
				'RED': black,
				'TAB': 'dmvpn',
				'GREEN THRESHOLD': 'DMVPN tunnels that are in the UP state',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'DMVPN tunnels that are in other than the UP state.',
				'RED THRESHOLD': black,
				},
			'Recent Route Convergence':{
                'CATEGORIES': white, 'CHECK NAME': 'Recent Route Convergence',
                'GREEN': recent_green,
                'BLUE': recent_blue,
				'AMBER': recent_amber,
				'RED': recent_red,
				'TAB': 'route-stability',
				'GREEN THRESHOLD': 'Routes with acceptable convergence',
				'BLUE THRESHOLD': 'With more than 30% of route occurrences that converged between '
								  'past 4 hours to 24 hours.',
				'AMBER THRESHOLD': 'With more than 30% of route occurrences that converged between '
								   'past 15 minutes to 4 hours',
				'RED THRESHOLD': 'With more than 30% of route occurrences that coverged in the '
								 'past 15 mins.',
				},
			'Stack Members Uptime':{
                'CATEGORIES': white, 'CHECK NAME': 'Stack Members Uptime',
                'GREEN': stack_uptime_green,
                'BLUE': stack_uptime_blue,
				'AMBER': stack_uptime_amber,
				'RED': stack_uptime_red,
				'TAB': 'stacks-members',
				'GREEN THRESHOLD': 'Stack member with uptime longer than 1 week and less than 3 years',
				'BLUE THRESHOLD': 'Stack members running for more than 3 years',
				'AMBER THRESHOLD': 'Stack member with uptime less than one week',
				'RED THRESHOLD': 'Stack members with uptime less than one day',
				},
			'SDWAN Sites Uptime':{
                'CATEGORIES': white, 'CHECK NAME': 'SDWAN Sites Uptime',
                'GREEN': sdwan_uptime_green,
                'BLUE': sdwan_uptime_blue,
				'AMBER': sdwan_uptime_amber,
				'RED': sdwan_uptime_red,
				'TAB': 'sdwan-sites',
				'GREEN THRESHOLD': 'Sites with uptime longer than 1 week and less than 3 years',
				'BLUE THRESHOLD': 'Sites running for more than 1 year',
				'AMBER THRESHOLD': 'Sites with uptime less than one week',
				'RED THRESHOLD': 'Sites with uptime less than one day',
				},
			'Security':{
                'CATEGORIES': 'Security', 'CHECK NAME': white,
                'GREEN': white,
                'BLUE': white,
				'AMBER': white,
				'RED': white,
				'TAB': white,
				'GREEN THRESHOLD': white,
				'BLUE THRESHOLD': white,
				'AMBER THRESHOLD': white,
				'RED THRESHOLD': white,
				},
			'IPSec Tunnel Status':{
                'CATEGORIES': white, 'CHECK NAME': 'IPSec Tunnel Status',
                'GREEN': ipsec_status_green,
                'BLUE': black,
				'AMBER': black,
				'RED': ipsec_status_red,
				'TAB': 'ipsec-tunnels',
				'GREEN THRESHOLD': 'IPsec tunnels that are in UP status.',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': 'IPsec tunnels that are in DOWN status.',
				},
			'IPSec Tunnel Authentication':{
                'CATEGORIES': white, 'CHECK NAME': 'IPSec Tunnel Authentication',
                'GREEN': ipsec_auth_green,
                'BLUE': black,
				'AMBER': ipsec_auth_amber,
				'RED': black,
				'TAB': 'ipcsec-tunnels',
				'GREEN THRESHOLD': 'IPsec tunnels with strong authentication',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'IPsec tunnels with weak authentication',
				'RED THRESHOLD': black,
				},
			'IPSec Gateway Status':{
                'CATEGORIES': white, 'CHECK NAME': 'IPSec Gateway Status',
                'GREEN': ipsec_gateway_green,
                'BLUE': black,
				'AMBER': black,
				'RED': ipsec_gateway_red,
				'TAB': 'ipsec-gateways',
				'GREEN THRESHOLD': 'IPsec gateways that are in  UP status',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': 'IPsec gateways that are in DOWN status.',
				},
			'IPSec Gateway Authentication':{
                'CATEGORIES': white, 'CHECK NAME': 'IPSec Gateway Authentication',
                'GREEN': ipsec_gateway_auth_green,
                'BLUE': black,
				'AMBER': ipsec_gateway_auth_amber,
				'RED': black,
				'TAB': 'ipsec-gateways',
				'GREEN THRESHOLD': 'IPsec gateways with strong authentication',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'IPsec gateways with weak authentication',
				'RED THRESHOLD': black,
				},
			'IPSec Tunnel Encryption':{
                'CATEGORIES': white, 'CHECK NAME': 'IPSec Tunnel Encryption',
                'GREEN': ipsec_enc_green,
                'BLUE': black,
				'AMBER': ipsec_enc_amber,
				'RED': black,
				'TAB': 'ipsec-tunnels',
				'GREEN THRESHOLD': 'IPsec tunnels with secure/strong encryption algorithms.',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'IPSec tunnels with insecure/weak encryption algorithm.',
				'RED THRESHOLD': black,
				},
			'IPSec Gateway Encryption':{
                'CATEGORIES': white, 'CHECK NAME': 'IPSec Gateway Encryption',
                'GREEN': ipsec_gwy_enc_green,
                'BLUE': black,
				'AMBER': ipsec_enc_amber,
				'RED': black,
				'TAB': 'ipsec-gateways',
				'GREEN THRESHOLD': 'IPSec gateways with secure/strong encryption algorithms.',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'IPSec gateways with insecure/weak encryption algorithm.',
				'RED THRESHOLD': black,
				},
			'MPLS Pseudo-wires':{
                'CATEGORIES': 'MPLS Pseudo-wires', 'CHECK NAME': white,
                'GREEN': white,
                'BLUE': white,
				'AMBER': white,
				'RED': white,
				'TAB': white,
				'GREEN THRESHOLD': white,
				'BLUE THRESHOLD': white,
				'AMBER THRESHOLD': white,
				'RED THRESHOLD': white,
				},
			'All Pseudowires state':{
                'CATEGORIES': white, 'CHECK NAME': 'All Pseudowires state',
                'GREEN': pseudo_green,
                'BLUE': pseudo_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'pseudowires',
				'GREEN THRESHOLD': 'Pseudowire state is UP',
				'BLUE THRESHOLD': 'Pseudowire state is DOWN',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'CCC state':{
                'CATEGORIES': white, 'CHECK NAME': 'CCC state',
                'GREEN': ccc_green,
                'BLUE': ccc_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'l2vpn-circuit-cross-connect',
				'GREEN THRESHOLD': "CCC circuit's state is UP",
				'BLUE THRESHOLD': "CCC circuit's state is UP",
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'PTP VPWS State':{
                'CATEGORIES': white, 'CHECK NAME': 'PTP VPWS State',
                'GREEN': ptp_vpws_green,
                'BLUE': ptp_vpws_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'l2vpn-point-to-point-vpws',
				'GREEN THRESHOLD': "VPWS circuit's state is UP",
				'BLUE THRESHOLD': 'VPWS circuit state is DOWN',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'PTMP VPLS State':{
                'CATEGORIES': white, 'CHECK NAME': 'PTMP VPLS State',
                'GREEN': ptmp_vpls_green,
                'BLUE': ptmp_vpls_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'l2vpn-point-to-multipoint',
				'GREEN THRESHOLD': 'VPLS circuits state is UP',
				'BLUE THRESHOLD': 'VPLS circuits state is DOWN',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'Neighborship compliance':{
                'CATEGORIES': 'Neighborship compliance', 'CHECK NAME': white,
                'GREEN': white,
                'BLUE': white,
				'AMBER': white,
				'RED': white,
				'TAB': white,
				'GREEN THRESHOLD': white,
				'BLUE THRESHOLD': white,
				'AMBER THRESHOLD': white,
				'RED THRESHOLD': white,
				},
			'STP Neighborship Expected State':{
                'CATEGORIES': white, 'CHECK NAME': 'STP Neighborship Expected State',
                'GREEN': stp_expected_green,
                'BLUE': stp_expected_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'stp-neighbors',
				'GREEN THRESHOLD': 'Spanning-Tree neighbors with expected port role states on each side of a '
								   'shared link (designated-alternate, root-designated).',
				'BLUE THRESHOLD': 'Spanning-Tree neighbors with other than expected port role states on each '
								  'side of shared link.',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'STP/CDP Neighbor Information Mismatch':{
                'CATEGORIES': white, 'CHECK NAME': 'STP/CDP Neighbor Information Mismatch',
                'GREEN': black,
                'BLUE': black,
				'AMBER': stpcdp_nei_mismatch_amber,
				'RED': black,
				'TAB': 'stp-cdp-ports-mismatch',
				'GREEN THRESHOLD': black,
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'Network devices with VLANs where no Spanning-Tree Protocol (STP) '
								   'is being detected.',
				'RED THRESHOLD': black,
				},
			'CDP/LLDP unidirectional':{
                'CATEGORIES': white, 'CHECK NAME': 'CDP/LLDP unidirectional',
                'GREEN': black,
                'BLUE': cdp_lldp_uni_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'unidirectional-neighbors',
				'GREEN THRESHOLD': black,
				'BLUE THRESHOLD': 'Unidirectional CDP or LLDP sessions.',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'CDP/LLDP Neighbor State':{
                'CATEGORIES': white, 'CHECK NAME': 'CDP/LLDP Neighbor State',
                'GREEN': cdp_lldp_nei_green,
                'BLUE': cdp_lldp_nei_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'all-neighbors',
				'GREEN THRESHOLD': 'Managed CDP or LLDP neighbors.',
				'BLUE THRESHOLD': 'Unmanaged CDP or LLDP neighbors.',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'OSPF Neighbor State':{
                'CATEGORIES': white, 'CHECK NAME': 'OSPF Neighbor State',
                'GREEN': ospf_nei_green,
                'BLUE': ospf_nei_blue ,
				'AMBER': ospf_nei_amber,
				'RED': ospf_nei_red,
				'TAB': 'ospf-neighbors',
				'GREEN THRESHOLD': 'OSPF neighbors with healthy state (FULL, 2WAY, ATTEMPT).',
				'BLUE THRESHOLD': 'OSPF neighbors with other than expected state.',
				'AMBER THRESHOLD': 'OSPF neighbors with transitive state (EXCHANGE,EXSTART,INIT, '
								   'LOADING)',
				'RED THRESHOLD': 'OSPF neighbors that are currently down.',
				},
			'OSPF Cost Consistency':{
                'CATEGORIES': white, 'CHECK NAME': 'OSPF Cost Consistency',
                'GREEN': ospf_cost_green,
                'BLUE': ospf_cost_blue,
				'AMBER': ospf_cost_amber,
				'RED': black,
				'TAB': 'ospf-neighbors',
				'GREEN THRESHOLD': 'OSPF sessions with equal local and neighbor cost.',
				'BLUE THRESHOLD': 'OSPF sessions with maximized local and neighbor cost (65535).',
				'AMBER THRESHOLD': 'OSPF sessions with unequal local and neighbor cost.',
				'RED THRESHOLD': black,
				},
			'OSPF Interface Neighbors':{
                'CATEGORIES': white, 'CHECK NAME': 'OSPF Interface Neighbors',
                'GREEN': ospf_int_green,
                'BLUE': ospf_int_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'ospf-interfaces',
				'GREEN THRESHOLD': 'OSPF enabled interfaces with one or more neighbors detected.',
				'BLUE THRESHOLD': 'OSPF enabled interfaces with zero neighbors detected.',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'OSPFv3 Neighbor State':{
                'CATEGORIES': white, 'CHECK NAME': 'OSPFv3 Neighbor State',
                'GREEN': ospfv3_nei_green,
                'BLUE': ospfv3_nei_blue,
				'AMBER': ospfv3_nei_amber,
				'RED': ospfv3_nei_red,
				'TAB': 'ospf-v3-neighbors',
				'GREEN THRESHOLD': 'OSPFv3 neighbors with healthy state (FULL, 2WAY, ATTEMPT).',
				'BLUE THRESHOLD': 'OSPFv3 neighbors with other than expected state.',
				'AMBER THRESHOLD': 'OSPFv3 neighbors with transitive state (EXCHANGE, EXSTART, INIT, LOADING).',
				'RED THRESHOLD': 'OSPFv3 neighbors that are currently down.',
				},
			'OSPFv3 Cost Consistency':{
                'CATEGORIES': white, 'CHECK NAME': 'OSPFv3 Cost Consistency',
                'GREEN': ospfv3_cost_green,
                'BLUE': ospfv3_cost_blue,
				'AMBER': ospfv3_cost_amber,
				'RED': black,
				'TAB': 'ospf-v3-neighbors',
				'GREEN THRESHOLD': 'OSPFv3 sessions with equal local and neighbor cost.',
				'BLUE THRESHOLD': 'OSPFv3 sessions with maximized local and neighbor cost (65535).',
				'AMBER THRESHOLD': 'OSPFv3 sessions with unequal local and neighbor cost.',
				'RED THRESHOLD': black,
				},
			'OSPFv3 Interface Neighbors':{
                'CATEGORIES': white, 'CHECK NAME': 'OSPFv3 Interface Neighbors',
                'GREEN': ospfv3_int_green,
                'BLUE': ospfv3_int_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'ospf-v3-interfaces',
				'GREEN THRESHOLD': 'OSPFv3 Interface Neighbors Detected',
				'BLUE THRESHOLD': 'OSPFv3 enabled interfaces with zero neighbors detected.',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'EIGRP Interface Neighbors':{
                'CATEGORIES': white, 'CHECK NAME': 'EIGRP Interface Neighbors',
                'GREEN': eigrp_int_green,
                'BLUE': eigrp_int_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'eigrp-interfaces',
				'GREEN THRESHOLD': 'EIGRP interfaces with one or more neighbors detected.',
				'BLUE THRESHOLD': 'EIGRP with zero neighbors detected',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'BGP Neighbor State':{
                'CATEGORIES': white, 'CHECK NAME': 'BGP Neighbor State',
                'GREEN': bgp_nei_green,
                'BLUE': bgp_nei_blue,
				'AMBER': bgp_nei_amber,
				'RED': bgp_nei_red,
				'TAB': 'bgp-neighbors',
				'GREEN THRESHOLD': 'BGP sessions in ESTABLISHED state.',
				'BLUE THRESHOLD': 'BGP sessions in other than expected state.',
				'AMBER THRESHOLD': 'BGP sessions in a transitive state (OPENSENT, OPENCONFIRM, '
								   'IDLE, CONNECT).',
				'RED THRESHOLD': 'BGP sessions in ACTIVE state.',
				},
			'BGP Received Prefixes':{
                'CATEGORIES': white, 'CHECK NAME': 'BGP Received Prefixes',
                'GREEN': bgp_rec_green,
                'BLUE': bgp_rec_blue,
				'AMBER': bgp_rec_amber,
				'RED': black,
				'TAB': 'bgp-neighbors',
				'GREEN THRESHOLD': 'Established BGP sessions with one or more received prefixes.',
				'BLUE THRESHOLD': 'Non-established BGP sessions with no received prefixes.',
				'AMBER THRESHOLD': 'Established BGP sessions with no received prefixes.',
				'RED THRESHOLD': black,
				},
			'IS-IS Interface Neighbors':{
                'CATEGORIES': white, 'CHECK NAME': 'IS-IS Interface Neighbors',
                'GREEN': isis_int_green,
                'BLUE': isis_int_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'is-is-interfaces',
				'GREEN THRESHOLD': 'IS-IS enabled interfaces with one or more neighbors detected.',
				'BLUE THRESHOLD': 'IS-IS enabled interfaces with zero neighbors detected.',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'RIP Interface Neighbors':{
                'CATEGORIES': white, 'CHECK NAME': 'RIP Interface Neighbors',
                'GREEN': rip_int_green,
                'BLUE': rip_int_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'rip-interfaces',
				'GREEN THRESHOLD': 'RIP interfaces with one or more neighbors detected.',
				'BLUE THRESHOLD': 'RIP interfaces with zero neighbors detected.',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'LDP Interface Neighbors':{
                'CATEGORIES': white, 'CHECK NAME': 'LDP Interface Neighbors',
                'GREEN': ldp_int_green,
                'BLUE': ldp_int_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'ldp-interfaces',
				'GREEN THRESHOLD': 'LDP enabled interfaces with one or more neighbors detected.',
				'BLUE THRESHOLD': 'LDP enabled interfaces with zero neighbors detected',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'PIM Interfaces Neighbors':{
                'CATEGORIES': white, 'CHECK NAME': 'PIM Interfaces Neighbors',
                'GREEN': pim_int_green,
                'BLUE': pim_int_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'pim-interfaces',
				'GREEN THRESHOLD': 'PIM enabled interfaces with one or more neighbors detected.',
				'BLUE THRESHOLD': 'PIM enabled interfaces with zero neighbors detected.',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'Unmanaged Neighbors':{
                'CATEGORIES': white, 'CHECK NAME': 'Unmanaged Neighbors',
                'GREEN': un_nei_green,
                'BLUE': black,
				'AMBER': un_nei_amber,
				'RED': un_nei_red,
				'TAB': 'unmanaged-neighbors',
				'GREEN THRESHOLD': 'Unmanaged neighbors detected with BGP protocol.',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'Unmanaged neighbors detected with interior gateway protocols.',
				'RED THRESHOLD': 'Unmanaged neighbors detected with discovery protocols.',
				},
			'Port-Channel Members State':{
                'CATEGORIES': white, 'CHECK NAME': 'Port-Channel Members State',
                'GREEN': pc_ms_green,
                'BLUE': pc_ms_blue,
				'AMBER': pc_ms_amber,
				'RED': black,
				'TAB': 'member-status-table',
				'GREEN THRESHOLD': 'Aggregated interfaces with healthy membership status UP, '
								   'Collecting Distributing, (P), (A) or SELECTED',
				'BLUE THRESHOLD': 'Aggregated interfaces with other than expected membership table',
				'AMBER THRESHOLD': 'Aggregated interfaces with membership status (S), (F), or (I).',
				'RED THRESHOLD': black,
				},
			'Trunk Allowed VLAN Mismatch':{
                'CATEGORIES': white, 'CHECK NAME': 'Trunk Allowed VLAN Mismatch',
                'GREEN': ta_vlm_green,
                'BLUE': black,
				'AMBER': black,
				'RED': ta_vlm_red,
				'TAB': 'neighbor-ports-vlan-mismatch',
				'GREEN THRESHOLD': 'Trunk links with equal number of allowed VLANs detected at each end.',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': 'VLANs mismatched on either side of the trunk.',
				},
			'Spanning-Tree Protocol (STP)':{
                'CATEGORIES': 'Spanning-Tree Protocol (STP)', 'CHECK NAME': white,
                'GREEN': white,
                'BLUE': white,
				'AMBER': white,
				'RED': white,
				'TAB': white,
				'GREEN THRESHOLD': white,
				'BLUE THRESHOLD': white,
				'AMBER THRESHOLD': white,
				'RED THRESHOLD': white,
				},
			'STP Virtual Port Status':{
                'CATEGORIES': white, 'CHECK NAME': 'STP Virtual Port Status',
                'GREEN': stp_virt_green,
                'BLUE': stp_virt_blue,
				'AMBER': stp_virt_amber,
				'RED': stp_virt_red,
				'TAB': 'stp-virtual-ports',
				'GREEN THRESHOLD': 'STP virtual ports with healthy status (Forwarding, Blocking, '
								   'Disabled, Discarding)',
				'BLUE THRESHOLD': 'STP virtual ports with unexpected status.',
				'AMBER THRESHOLD': 'STP virtual ports with non-healthy or transit status (Broken, Learn, Listen).',
				'RED THRESHOLD': 'STP virtual ports with non-healthy Discard status while is Designated state.',
				},
			'Switchport VLANs Without STP':{
                'CATEGORIES': white, 'CHECK NAME': 'Switchport VLANs Without STP',
                'GREEN': black,
                'BLUE': black,
				'AMBER': sw_no_stp_amber,
				'RED': black,
				'TAB': 'stp-inconsistencies',
				'GREEN THRESHOLD': black,
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'Network devices with VLANs where no Spanning-Tree Protocol (STP) is being detected.',
				'RED THRESHOLD': black,
				},
			'STP Loops':{
                'CATEGORIES': white, 'CHECK NAME': 'STP Loops',
                'GREEN': stp_loops_green,
                'BLUE': black,
				'AMBER': stp_loops_amber,
				'RED': black,
				'TAB': 'stp-neighbors',
				'GREEN THRESHOLD': 'Spanning-Tree relationships with no loops detected.',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'Spanning-Tree relationships with loops detected.',
				'RED THRESHOLD': black,
				},
			'STP Ports with Multiple Neighbors':{
                'CATEGORIES': white, 'CHECK NAME': 'STP Ports with Multiple Neighbors',
                'GREEN': black,
                'BLUE': black,
				'AMBER': stp_multiple_nei_amber,
				'RED': black,
				'TAB': 'stp-ports-multiple-neighbors',
				'GREEN THRESHOLD': black,
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'Network ports using Spanning-Tree Protocol (STP) with more than one STP neighbor.',
				'RED THRESHOLD': black,
				},
			'Old STP Versions':{
                'CATEGORIES': white, 'CHECK NAME': 'Old STP Versions',
                'GREEN': old_stp_green,
                'BLUE': old_stp_blue,
				'AMBER': old_stp_amber,
				'RED': old_stp_red,
				'TAB': 'stp-bridges',
				'GREEN THRESHOLD': 'STP Mode equals rapid-pvst',
				'BLUE THRESHOLD': 'STP Mode equals rstp',
				'AMBER THRESHOLD': 'STP Mode equals pvst',
				'RED THRESHOLD': 'STP mode equals mst or mstp',
				},
			'Multiple STP Links Between Two Devices':{
                'CATEGORIES': white, 'CHECK NAME': 'Multiple STP Links Between Two Devices',
                'GREEN': black,
                'BLUE': black,
				'AMBER': mult_stp_amber,
				'RED': black,
				'TAB': 'stp-multiple-stp',
				'GREEN THRESHOLD': black,
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'Network devices with multiple shared Spanning-Tree Protocol links.',
				'RED THRESHOLD': black,
				},
			'VLAN status verification':{
                'CATEGORIES': white, 'CHECK NAME': 'VLAN status verification',
                'GREEN': vlan_status_green,
                'BLUE': vlan_status_blue,
				'AMBER': vlan_status_amber,
				'RED': black,
				'TAB': 'stp-vlans',
				'GREEN THRESHOLD': 'Active VLANs',
				'BLUE THRESHOLD': 'System VLANs',
				'AMBER THRESHOLD': 'Inactive VLANs',
				'RED THRESHOLD': black,
				},
			'VLAN Names':{
                'CATEGORIES': white, 'CHECK NAME': 'VLAN Names',
                'GREEN': vlan_names_green,
                'BLUE': vlan_names_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'stp-names',
				'GREEN THRESHOLD': 'VLANs with detected Name or Description',
				'BLUE THRESHOLD': 'VLANs without any detected Name or Description',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'SPT mode PVST or disabled':{
                'CATEGORIES': white, 'CHECK NAME': 'SPT mode PVST or disabled',
                'GREEN': black,
                'BLUE': stp_pvst_disabled_blue,
				'AMBER': stp_pvst_disabled_amber,
				'RED': black,
				'TAB': 'stp-bridges',
				'GREEN THRESHOLD': black,
				'BLUE THRESHOLD': 'STP disabled',
				'AMBER THRESHOLD': 'STP in PVST mode',
				'RED THRESHOLD': black,
				},
			'Managed IP Address DNS Consistency':{
                'CATEGORIES': white, 'CHECK NAME': 'Managed IP Address DNS Consistency',
                'GREEN': ip_dns_green,
                'BLUE': ip_dns_blue,
				'AMBER': ip_dns_amber,
				'RED': black,
				'TAB': 'managed-ip',
				'GREEN THRESHOLD': 'Network devices with matching hostname with DNS and '
								   'also the A/CNAME record.',
				'BLUE THRESHOLD': 'Network devices with no matching hostname with DNS or '
								  'the A/CNAME record.',
				'AMBER THRESHOLD': 'Network devices with no matching hostname with DNS and '
								   'no matching A/CNAME record.',
				'RED THRESHOLD': black,
				},
			'MAC Address Source':{
                'CATEGORIES': white, 'CHECK NAME': 'MAC Address Source',
                'GREEN': mac_source_green,
                'BLUE': mac_source_blue,
				'AMBER': mac_source_amber,
				'RED': black,
				'TAB': 'mac-table',
				'GREEN THRESHOLD': 'Media Access Control records with an expected dynamic sources '
								   '(learn, dynamic, evpn, d, dl, dlr).',
				'BLUE THRESHOLD': 'Media Access Control records from unexpected source.',
				'AMBER THRESHOLD': 'Media Access Control records with source static or self.',
				'RED THRESHOLD': black,
				},
			'Proxy ARP':{
                'CATEGORIES': white, 'CHECK NAME': 'Proxy ARP',
                'GREEN': proxy_arp_green,
                'BLUE': proxy_arp_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'arp-table',
				'GREEN THRESHOLD': 'ddress Resolution Protocol records without Proxy ARP detected.',
				'BLUE THRESHOLD': 'Address Resultion Protocol records with Proxy ARP detected.',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'Duplicate IP Addresses':{
                'CATEGORIES': white, 'CHECK NAME': 'Duplicate IP Addresses',
                'GREEN': black,
                'BLUE': dupe_ip_blue,
				'AMBER': dupe_ip_amber,
				'RED': black,
				'TAB': 'duplicate-ip',
				'GREEN THRESHOLD': black,
				'BLUE THRESHOLD': 'Duplicate IP  addresses with 2 occurrences.',
				'AMBER THRESHOLD': 'Duplicate IP addresses with more than 2 occurrences.',
				'RED THRESHOLD': black,
				},
			'Management Consistency':{
                'CATEGORIES': 'Management Consistency', 'CHECK NAME': white,
                'GREEN': white,
                'BLUE': white,
				'AMBER': white,
				'RED': white,
				'TAB': white,
				'GREEN THRESHOLD': white,
				'BLUE THRESHOLD': white,
				'AMBER THRESHOLD': white,
				'RED THRESHOLD': white,
				},
			'AAA Authorization Method':{
                'CATEGORIES': white, 'CHECK NAME': 'AAA Authorization Method',
                'GREEN': aaa_author_green,
                'BLUE': black,
				'AMBER': aaa_author_amber,
				'RED': black,
				'TAB': 'aaa-authorization',
				'GREEN THRESHOLD': 'Specifies Authorization Method',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'Does Not Specify Authorization Method',
				'RED THRESHOLD': black,
				},
			'AAA Accounting Method':{
                'CATEGORIES': white, 'CHECK NAME': 'AAA Accounting Method',
                'GREEN': aaa_acc_green,
                'BLUE': black,
				'AMBER': aaa_acc_amber,
				'RED': black,
				'TAB': 'aaa-accounting',
				'GREEN THRESHOLD': 'Specifies Accounting Method',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'Does Not Specify Accounting Method',
				'RED THRESHOLD': black,
				},
			'AAA Authentication Method':{
                'CATEGORIES': white, 'CHECK NAME': 'AAA Authentication Method',
                'GREEN': aaa_authe_green,
                'BLUE': black,
				'AMBER': aaa_authe_amber,
				'RED': black,
				'TAB': 'aaa-authentication',
				'GREEN THRESHOLD': 'Specifies Authentication Method',
				'BLUE THRESHOLD': '',
				'AMBER THRESHOLD': 'Does Not Specify Authentication Method',
				'RED THRESHOLD': '',
				},
			'NTP Stratum Level':{
                'CATEGORIES': white, 'CHECK NAME': 'NTP Stratum Level',
                'GREEN': ntp_stratum_green,
                'BLUE': ntp_stratum_blue,
				'AMBER': ntp_stratum_amber,
				'RED': ntp_stratum_red,
				'TAB': 'ntp-sources',
				'GREEN THRESHOLD': 'NTP sources with Stratum value lower than 4.',
				'BLUE THRESHOLD': 'NTP sources with Stratum value 4 or 5',
				'AMBER THRESHOLD': 'NTP sources with Stratum between 5 and 16.',
				'RED THRESHOLD': 'NTP sources with Stratum between 5 and 16.',
				},
			'NTP Time Offset':{
                'CATEGORIES': white, 'CHECK NAME': 'NTP Time Offset',
                'GREEN': ntp_offset_green,
                'BLUE': ntp_offset_blue,
				'AMBER': ntp_offset_amber,
				'RED': ntp_offset_red,
				'TAB': 'ntp-sources',
				'GREEN THRESHOLD': 'NTP sources with Time Offset less than 100ms.',
				'BLUE THRESHOLD': 'NTP sources with Time Offset more than 100ms and '
								  'less than 500ms.',
				'AMBER THRESHOLD': 'NTP sources with Time Offsetmore than 500ms and '
								   'less than 1000ms.',
				'RED THRESHOLD': 'NTP sources with Time Offset more above 1000ms.',
				},
			'NTP Network Round-Trip Time':{
                'CATEGORIES': white, 'CHECK NAME': 'NTP Network Round-Trip Time',
                'GREEN': ntp_rtt_green,
                'BLUE': ntp_rtt_blue,
				'AMBER': ntp_rtt_amber,
				'RED': ntp_rtt_red,
				'TAB': 'ntp-sources',
				'GREEN THRESHOLD': 'NTP sources with Round Trip Time lower than 50ms.',
				'BLUE THRESHOLD': 'NTP sources with Round Trip Time value within 50-100ms.',
				'AMBER THRESHOLD': 'NTP sources with Round Trip Time value within 100-500ms.',
				'RED THRESHOLD': 'NTP sources with RTT above 500ms',
				},
			'Remote System Logging Destination Port':{
                'CATEGORIES': white, 'CHECK NAME': 'Remote System Logging Destination Port',
                'GREEN': remote_logg_green,
                'BLUE': remote_logg_blue,
				'AMBER': remote_logg_amber,
				'RED': black,
				'TAB': 'logging-remote',
				'GREEN THRESHOLD': 'Destination syslog hosts with destination port 514',
				'BLUE THRESHOLD': 'Destination syslog hosts with destination port other than '
								  '514 and not within the well-known network port range.',
				'AMBER THRESHOLD': 'Destination syslog hosts with destination port other than 514'
								   ' and within the well-known port range.',
				'RED THRESHOLD': black,
				},
			'SNMP Community Name':{
                'CATEGORIES': white, 'CHECK NAME': 'SNMP Community Name',
                'GREEN': snmp_name_green,
                'BLUE': black,
				'AMBER': snmp_name_amber,
				'RED': black,
				'TAB': 'snmp-communities',
				'GREEN THRESHOLD': 'SNMP communities that have not been left with default name.',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'SNMP communities that are left with default name PUBLIC or PRIVATE.',
				'RED THRESHOLD': black,
				},
			'SNMP Configuration Compliance':{
                'CATEGORIES': white, 'CHECK NAME': 'SNMP Configuration Compliance',
                'GREEN': snmp_config_green,
                'BLUE': snmp_config_blue,
				'AMBER': snmp_config_amber,
				'RED': black,
				'TAB': 'snmp-summary',
				'GREEN THRESHOLD': 'Devices with at least one configured SNMP user and with at least '
								   'one configured SNMP community.',
				'BLUE THRESHOLD': 'Devices with at least one configured SNMP user or with at least '
								  'one configured SNMP community.',
				'AMBER THRESHOLD': 'Devices with no SNMP user and no SNMP community configured.',
				'RED THRESHOLD': black,
				},
			'Saved Config Consistency':{
                'CATEGORIES': white, 'CHECK NAME': 'Saved Config Consistency',
                'GREEN': config_con_green,
                'BLUE': config_con_blue,
				'AMBER': config_con_amber,
				'RED': black,
				'TAB': 'saved-config-consistency',
				'GREEN THRESHOLD': 'Network devices with saved running configuration',
				'BLUE THRESHOLD': 'Devices where check was not performed if the configuration '
								  'was saved',
				'AMBER THRESHOLD': 'Network devices with unsaved configuration, having different'
								   'runningand startup configurations.',
				'RED THRESHOLD': black,
				},
			'DHCP Snooping Dropped Packets':{
                'CATEGORIES': white, 'CHECK NAME': 'DHCP Snooping Dropped Packets',
                'GREEN': dhcp_dropped_green,
                'BLUE': black	,
				'AMBER': dhcp_dropped_amber,
				'RED': black,
				'TAB': 'dhcp-snooping',
				'GREEN THRESHOLD': 'Represents devices with enabled DHCP Snooping without dropped'
								   'packets detected.',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'Represents devices with enabled DHCP Snoopingwith dropped packets '
								   'detected.',
				'RED THRESHOLD': black,
				},
			'DHCP Snooping Trusted Port':{
                'CATEGORIES': white, 'CHECK NAME': 'DHCP Snooping Trusted Port',
                'GREEN': dhcp_trusted_green,
                'BLUE': black,
				'AMBER': black,
				'RED': dhcp_trusted_red,
				'TAB': 'dhcp-snooping',
				'GREEN THRESHOLD': 'Represents devices with enabled DHCP Snooping with available trusted port',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': 'Represents devices with enabled DHCP Snooping without an available trusted port',
				},
			'DHCP Snooping Enabled VLANs':{
                'CATEGORIES': white, 'CHECK NAME': 'DHCP Snooping Enabled VLANs',
                'GREEN': dhcp_enabled_green,
                'BLUE': black,
				'AMBER': black,
				'RED': dhcp_enabled_red,
				'TAB': 'dhcp-snooping',
				'GREEN THRESHOLD': 'Represents devices with enabled DHCP Snooping on any number of VLANs',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': 'Represents devices with enabled DHCP Snooping with no enabled VLANs.',
				},
			'DHCP Binding session expiration':{
                'CATEGORIES': white, 'CHECK NAME': 'DHCP Binding session expiration',
                'GREEN': dhcp_binding_green,
                'BLUE': dhcp_binding_blue,
				'AMBER': dhcp_binding_amber,
				'RED': dhcp_binding_red,
				'TAB': 'dhcp-bindings',
				'GREEN THRESHOLD': 'Represents DHCP binding session with session expiration time greater '
								   'than 300 seconds',
				'BLUE THRESHOLD': 'Represents DHCP binding session with session expiration time within 300 and '
								  '180 seconds, or unknown.',
				'AMBER THRESHOLD': 'Represents DHCP binding session with session expiration time within 180 and '
								   '60 seconds.',
				'RED THRESHOLD': 'Represents DHCP binding session wtih session expiration time elss than 60 '
								 'seconds.',
				},
			'AAA Authentication Type':{
                'CATEGORIES': white, 'CHECK NAME': 'AAA Authentication Type',
                'GREEN': aaa_authe_type_green,
                'BLUE': aaa_authe_type_blue,
				'AMBER': aaa_authe_type_amber,
				'RED': aaa_authe_type_red,
				'TAB': 'aaa-lines',
				'GREEN THRESHOLD': 'Lines with default AAA authentication method.',
				'BLUE THRESHOLD': 'Lines with local authentication method, signifying the use of username and '
								  'password configured locally on the device.',
				'AMBER THRESHOLD': 'Lines with line authentication, signifying password configured directly '
								   'on the line.',
				'RED THRESHOLD': 'Lines with no authentication method, allowing unauthenticated access.',
				},
			'SNMP Community & ACL':{
                'CATEGORIES': white, 'CHECK NAME': 'SNMP Community & ACL',
                'GREEN': snmp_acl_green,
                'BLUE': snmp_acl_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'snmp-communities',
				'GREEN THRESHOLD': 'SNMP Communities with configured ACL.',
				'BLUE THRESHOLD': 'SNMP Communities without configured ACL.',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'Local System Logging Severity':{
                'CATEGORIES': white, 'CHECK NAME': 'Local System Logging Severity',
                'GREEN': local_logg_green,
                'BLUE': black,
				'AMBER': local_logg_amber,
				'RED': black,
				'TAB': 'logging-local',
				'GREEN THRESHOLD': 'Devices with local syslog server configuration that do not have DEBUG enabled.',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'Devices with local syslog server configuration that have DEBUG enabled.',
				'RED THRESHOLD': black,
				},
			'Remote System Logging Severity':{
                'CATEGORIES': white, 'CHECK NAME': 'Remote System Logging Severity',
                'GREEN': remote_sys_logg_green,
                'BLUE': black,
				'AMBER': remote_sys_logg_amber,
				'RED': black,
				'TAB': 'logging-remote',
				'GREEN THRESHOLD': 'Devices with remote syslog server',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'Devices with remote syslog server configuration that have DEBUG enabled.',
				'RED THRESHOLD': black,
				},
			'NTP Reachable Sources':{
                'CATEGORIES': white, 'CHECK NAME': 'NTP Reachable Sources',
                'GREEN': ntp_reachable_green,
                'BLUE': ntp_reachable_blue,
				'AMBER': ntp_reachable_amber,
				'RED': ntp_reachable_red,
				'TAB': 'ntp-summary',
				'GREEN THRESHOLD': 'Device has Reachable NTP Sources',
				'BLUE THRESHOLD': 'Network devices with at least 1 configured source and 1 reachable source.',
				'AMBER THRESHOLD': 'Network devices with no configured source and no reachable source.',
				'RED THRESHOLD': 'Network devices with at least 1 configured source and no reachable source.',
				},
			'Devices with Telnet Access (total)':{
                'CATEGORIES': white, 'CHECK NAME': 'Devices with Telnet Access (total)',
                'GREEN': black,
                'BLUE': black,
				'AMBER': black,
				'RED': telnet_red,
				'TAB': 'telnet-access',
				'GREEN THRESHOLD': black,
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': 'Devices that allow telnet or have the telnet feature enabled.',
				},
			'Device Logging Configuration':{
                'CATEGORIES': white, 'CHECK NAME': 'Device Logging Configuration',
                'GREEN': device_logg_green,
                'BLUE': black,
				'AMBER': device_logg_amber,
				'RED': device_logg_red,
				'TAB': 'logging-summary',
				'GREEN THRESHOLD': 'Network devices with at least one remote and one local logging configured.',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'Network devices with one remote or local logging configured.',
				'RED THRESHOLD': 'Devices with no remote and no local logging configured.',
				},
			'NTP Configured Sources':{
                'CATEGORIES': white, 'CHECK NAME': 'NTP Configured Sources',
                'GREEN': ntp_sources_green,
                'BLUE': black,
				'AMBER': ntp_sources_amber,
				'RED': ntp_sources_red,
				'TAB': 'ntp-summary',
				'GREEN THRESHOLD': 'Network devices with 2 or 3 configured NTP soruces.',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'Network devices with only 1 or more than 3 configured NTP sources.',
				'RED THRESHOLD': 'Network devices with 0 configured NTP sources.',
				},
			'Operating System (OS)':{
                'CATEGORIES': 'Operating System (OS)', 'CHECK NAME': white,
                'GREEN': white,
                'BLUE': white,
				'AMBER': white,
				'RED': white,
				'TAB': white,
				'GREEN THRESHOLD': white,
				'BLUE THRESHOLD': white,
				'AMBER THRESHOLD': white,
				'RED THRESHOLD': white,
				},
			'Operating System Version (%)':{
                'CATEGORIES': white, 'CHECK NAME': 'Operating System Version (%)',
                'GREEN': os_ver_green,
                'BLUE': os_ver_blue,
				'AMBER': os_ver_amber,
				'RED': os_ver_red,
				'TAB': 'os-versions',
				'GREEN THRESHOLD': 'Platforms with the same operating system, that is installed on more '
								   'than 30% of the platform.',
				'BLUE THRESHOLD': 'Platforms  with the same operating system, that is installed within 30% '
								  'and 20% of the platform.',
				'AMBER THRESHOLD': 'Platforms with the same operating system, that is installed within 20% '
								   'and 10% of the platform.',
				'RED THRESHOLD': 'Platforms with the same operating system, that is installed on less than '
								 '10% of the platform.',
				},
			'Devices with Unique OS':{
                'CATEGORIES': white, 'CHECK NAME': 'Devices with Unique OS',
                'GREEN': unique_os_green,
                'BLUE': unique_os_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'os-versions',
				'GREEN THRESHOLD': 'Network devices with non-unique installed operating system.',
				'BLUE THRESHOLD': 'Network devices with unique installed operating system.',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'Devices with Unique Platform':{
                'CATEGORIES': white, 'CHECK NAME': 'Devices with Unique Platform',
                'GREEN': unique_platform_green,
                'BLUE': unique_platform_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'os-versions',
				'GREEN THRESHOLD': 'Network devices with non-unique platform',
				'BLUE THRESHOLD': 'Network devices with unique platform.',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'Quality of Service (QoS)':{
                'CATEGORIES': 'Quality of Service (QoS)', 'CHECK NAME': white,
                'GREEN': white,
                'BLUE': white,
				'AMBER': white,
				'RED': white,
				'TAB': white,
				'GREEN THRESHOLD': white,
				'BLUE THRESHOLD': white,
				'AMBER THRESHOLD': white,
				'RED THRESHOLD': white,
				},
			'QoS Random And Tail Drops':{
                'CATEGORIES': white, 'CHECK NAME': 'QoS Random And Tail Drops',
                'GREEN': qos_random_tail_green,
                'BLUE': qos_random_tail_blue,
				'AMBER': qos_random_tail_amber,
				'RED': qos_random_tail_red,
				'TAB': 'random-drops',
				'GREEN THRESHOLD': '',
				'BLUE THRESHOLD': '',
				'AMBER THRESHOLD': '',
				'RED THRESHOLD': '',
				},
			'QoS EF Class Drops':{
                'CATEGORIES': white, 'CHECK NAME': 'QoS EF Class Drops',
                'GREEN': qos_ef_drops_green,
                'BLUE': black,
				'AMBER': qos_ef_drops_amber,
				'RED': black,
				'TAB': 'policy-map',
				'GREEN THRESHOLD': 'Classes carrying Expedited Forwarding traffic with drop rate equal to 0',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'Classes carrying Expedited Forwarding traffic with drop rate greater than 0',
				'RED THRESHOLD': black,
				},
			'QoS Priority Queue Drops':{
                'CATEGORIES': white, 'CHECK NAME': 'QoS Priority Queue Drops',
                'GREEN': qos_pri_drops_green,
                'BLUE': black,
				'AMBER': qos_pri_drops_amber,
				'RED': black,
				'TAB': 'priority-queuing',
				'GREEN THRESHOLD': 'QoS priority classes without any drops detected.',
				'BLUE THRESHOLD': black,
				'AMBER THRESHOLD': 'QoS priority classes with drops detected',
				'RED THRESHOLD': black,
				},
			'Queue Limit Size (packets)':{
                'CATEGORIES': white, 'CHECK NAME': 'Queue Limit Size (packets)',
                'GREEN': q_limit_size_green,
                'BLUE': q_limit_size_blue,
				'AMBER': q_limit_size_amber,
				'RED': black,
				'TAB': 'queuing',
				'GREEN THRESHOLD': 'QoS class with queue-limit size that is below 64 packets.',
				'BLUE THRESHOLD': 'QoS classes with queue-limit size between 64 and 256 packets.',
				'AMBER THRESHOLD': 'QoS classes with queue-limit size greater than 256 packets.',
				'RED THRESHOLD': black,
				},
			'Shaping Queues Child Policy':{
                'CATEGORIES': white, 'CHECK NAME': 'Shaping Queues Child Policy',
                'GREEN': shaping_child_green,
                'BLUE': shaping_child_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'shaping',
				'GREEN THRESHOLD': 'Shaping queues with child policy configured.',
				'BLUE THRESHOLD': 'Shaping queus without any child policy configured.',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'First Hop Redundancy Protocol (FHRP)':{
                'CATEGORIES': 'First Hop Redundancy Protocol (FHRP)', 'CHECK NAME': white,
                'GREEN': white,
                'BLUE': white,
				'AMBER': white,
				'RED': white,
				'TAB': white,
				'GREEN THRESHOLD': white,
				'BLUE THRESHOLD': white,
				'AMBER THRESHOLD': white,
				'RED THRESHOLD': white,
				},
			'Gateway Redundancy':{
                'CATEGORIES': white, 'CHECK NAME': 'Gateway Redundancy',
                'GREEN': gwy_redu_green,
                'BLUE': gwy_redu_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'gateway-redundancy',
				'GREEN THRESHOLD': 'IP Subnets with more than one gateway with at least one user/endpoint.',
				'BLUE THRESHOLD': 'IP subnets with only one gateway with at least one user/endpoint.',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'Virtual Gateways Consistency':{
                'CATEGORIES': white, 'CHECK NAME': 'Virtual Gateways Consistency',
                'GREEN': virt_gwy_green,
                'BLUE': virt_gwy_blue,
				'AMBER': virt_gwy_amber ,
				'RED': black,
				'TAB': 'gateway-redundancy',
				'GREEN THRESHOLD': 'IP Subnets with two ore more gateways and one virtual gateway with '
								   'active endpoints or IP subnets with no active endpoints.',
				'BLUE THRESHOLD': 'IP subnets with zero virtual gateways or IP subnets with one physical '
								  'gateway with less that 20 active endpoints.',
				'AMBER THRESHOLD': 'IP subnets with two or more virtual gateways or IP subnets with no '
								   'virtual gateway with mroe than 20 active endpoints.',
				'RED THRESHOLD': black,
				},
			'FHRP Active Group Priority':{
                'CATEGORIES': white, 'CHECK NAME': 'FHRP Active Group Priority',
                'GREEN': fhrp_active_green,
                'BLUE': fhrp_active_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'group-state',
				'GREEN THRESHOLD': 'Active FHRP groups with priority value greater than 100.',
				'BLUE THRESHOLD': 'Active FHRP groups with priority value of 100 (default) or lower.',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'FHRP Group Members':{
                'CATEGORIES': white, 'CHECK NAME': 'FHRP Group Members',
                'GREEN': fhrp_members_green,
                'BLUE': fhrp_members_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'group-members',
				'GREEN THRESHOLD': 'FHRP groups with expected number of members',
				'BLUE THRESHOLD': 'FHRP groups with unexpected number of members.',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'STP Root And FHRP Active Mismatch':{
                'CATEGORIES': white, 'CHECK NAME': 'STP Root And FHRP Active Mismatch',
                'GREEN': black,
                'BLUE': stp_fhrp_mismatch_blue,
				'AMBER': black,
				'RED': black,
				'TAB': 'active-gw-root-alignment',
				'GREEN THRESHOLD': black,
				'BLUE THRESHOLD': 'Active FHRP gateways that are not aligned with the Spanning-Tree '
								  'Protocol Root Bridge',
				'AMBER THRESHOLD': black,
				'RED THRESHOLD': black,
				},
			'FHRP Master Inconsistency':{
                'CATEGORIES': white, 'CHECK NAME': 'FHRP Master Inconsistency',
                'GREEN': fhrp_master_green,
                'BLUE': fhrp_master_blue,
				'AMBER': fhrp_master_amber,
				'RED': fhrp_master_red,
				'TAB': 'group-members',
				'GREEN THRESHOLD': 'FHRP group with one master',
				'BLUE THRESHOLD': 'Default',
				'AMBER THRESHOLD': 'FHRP master appear more tha once',
				'RED THRESHOLD': 'No master detected',
				},
}

